# Generated by Django 4.1.1 on 2022-10-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersconfig',
            name='departure_frequency',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordersconfig',
            name='logistic_days',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordersconfig',
            name='max_size_girth',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordersconfig',
            name='max_size_width',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordersconfig',
            name='max_weight',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordersconfig',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordersconfig',
            name='traking_link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordersconfig',
            name='volume_weight',
            field=models.CharField(max_length=255),
        ),
    ]
