# Generated by Django 4.1.1 on 2022-10-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_alter_ordersconfig_departure_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersconfig',
            old_name='max_size_girth',
            new_name='max_size',
        ),
        migrations.RemoveField(
            model_name='ordersconfig',
            name='max_size_width',
        ),
    ]
