# Generated by Django 4.1.1 on 2022-10-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_rename_max_size_girth_ordersconfig_max_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['created'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='ordersconfig',
            options={'ordering': ['title'], 'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукции'},
        ),
        migrations.AlterModelOptions(
            name='orderstatistics',
            options={'verbose_name': 'Статистика сайта', 'verbose_name_plural': 'Статистики сайта'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['date'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name': 'Соц.сеть', 'verbose_name_plural': 'Соц.сети'},
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='tg_admin_group_id',
            field=models.CharField(blank=True, help_text='ID группы должен начинаться с -100', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='tg_bot_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
